<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ config('app.name') }}</title>
    <style>
        /* General Styles */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        /* Header Styles */
        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header img {
            width: 100px; /* Adjust logo size */
        }

        .header h1 {
            margin: 10px 0;
            font-size: 24px;
            color: orangered;
        }

        .header p {
            margin: 5px 0;
            font-size: 14px;
            color: #666;
        }

        /* Table Styles */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th, td {
            border: 1px solid #000;
            padding: 10px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        /* Footer Styles */
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 12px;
            color: #666;
            border-top: 1px solid #000;
            padding: 10px;
            background-color: #fff;
        }

        .footer .page-number:after {
            content: "Page " counter(page);
        }

        /* Page Break Handling */
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>{{ config('app.name') }}</h1>
        <p>Order Report</p>
        <p>Generated on: {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>

    <!-- Table -->
    <table>
        <thead>
            <tr>
                <th>Order No.</th>
                <th>Order Date</th>
                <th>Amount</th>
                <th>Discount</th>
                <th>Tax</th>
            </tr>
        </thead>
        <tbody>
            @foreach($orders as $order)
                <tr>
                    <td>{{ $order->order_id }}</td>
                    <td>{{ $order->order_date }}</td>
                    <td>{{ $order->total_amount }}</td>
                    <td>{{ $order->discount ?? '0'}}</td>
                    <td>{{ $order->tax ?? '0'}}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <!-- Footer -->
    <div class="footer">
        <p>Generated by {{ config('app.name') }} | <span class="page-number"></span></p>
    </div>
</body>
</html>